#!/usr/bin/env racket
#lang scheme

(define (forth)
  ; Forth registers.
  (define ip 0)
  (define evec #())
  (define sp '())
  (define rp '())
  (define work '())

  ; Core operations.
  (define (next)
    (set! work (vector-ref evec ip))
    (set! ip (+ 1 ip))
    ((car work)))
  (define (docol)
    (set! rp (cons (cons ip evec) rp))
    (set! ip 0)
    (set! evec (entry-data work))
    (next))
  (define (doexit)
    (set! ip (caar rp))
    (set! evec (cdar rp))
    (set! rp (cdr rp))
    (next))
  (define (dolit)
    (set! sp (cons (vector-ref evec ip) sp))
    (set! ip (+ 1 ip))
    (next))

  ; String helper procedures.
  (define (empty-string? s) (= 0 (string-length s)))
  (define (first s) (substring s 0 1))
  (define (rest s) (substring s 1))

  ; Parsing (stateless).
  (define (parse line separator k)
    (define (skip line)
      (cond ((empty-string? line) line)
            ((string=? (first line) separator) (skip (rest line)))
            (else line)))
    (define (iter i line)
      (cond ((empty-string? line) (k i line))
            ((string=? (first line) separator) (k i (rest line)))
            (else (iter (string-append i (first line)) (rest line)))))
    (iter "" (skip line)))
  ; Stateful parsing.
  (define line "")
  (define (parse! sep)
    (parse line sep (lambda (name rest)
      (set! line rest)
      name)))

  ; Compilation state.
  (define definition #())
  (define definition-name "")
  (define state 0)

  ; Colon definitions.
  (define (compile)
    (set! state 1)
    (next))
  (define (interpret)
    (set! state 0)
    (next))
  (define (colon)
    (set! definition-name (parse! " "))
    (set! definition #())
    (compile))
  (define (semicolon)
    (set! definition (vector-append definition (vector (find "exit"))))
    (dictionary! (make-data-word definition-name docol definition))
    (interpret))

  ; Immediates.
  (define (immediate)
    (define entry (car dictionary))
    (set! dictionary (cdr dictionary))
    (dictionary! (into-immediate entry))
    (next))
  (define (comment)
    (parse! ")")
    (next))
  (define (dostring)
    (define str (parse! "\""))
    (if (= 0 state)
        (set! sp (cons str sp))
        (set! definition (vector-append definition (vector (make-word "dolit" dolit) str))))
    (next))

  ; Word entry structure
  (define (make-entry name action flags data) (list action data name flags))
  (define (entry-action entry) (car entry))
  (define (entry-data entry) (cadr entry))
  (define (entry-name entry) (caddr entry))
  (define (entry-flags entry) (cadddr entry))
  (define (entry-immediate? entry) (= 1 (entry-flags entry)))

  ; Dictionary manipulation.
  (define (make-word name action) (make-entry name action 0 '()))
  (define (make-immediate name action) (make-entry name action 1 '()))
  (define (make-data-word name action data) (make-entry name action 0 data))
  (define (dictionary! entry) (set! dictionary (cons entry dictionary)))
  (define (into-immediate entry) (make-entry (entry-name entry) (entry-action entry)
                                             (entry-flags entry) (entry-data entry)))
  (define (find name)
    (define (iter i)
      (cond ((null? i) '())
            ((string=? name (entry-name (car i))) (car i))
            (else (iter (cdr i)))))
    (iter dictionary))

  ; Word debugging.
  (define (see)
    (define name (parse! " "))
    (define entry (find name))
    (if (eq? (entry-action entry) docol)
        (see-colon entry)
        (see-other entry))
    (next))
  (define (see-colon entry)
    (display ": ")
    (display (entry-name entry))
    (display "  ")
    (define data (entry-data entry))
    (define (iter i)
      (cond ((= i (vector-length data)) '())
            ((pair? (vector-ref data i)) (begin (display (entry-name (vector-ref data i)))
                                                (display " ")
                                                (iter (+ i 1))))
            (else (begin (display (list (vector-ref data i)))
                         (display " ")
                         (iter (+ i 1))))))
    (iter 0)
    (newline))
  (define (see-other entry)
    (display entry)
    (newline))
  ; Whole dictionary debugging.
  (define (words)
    (define (iter i)
      (if (null? i)
        '()
        (begin (display (entry-name (car i)))
               (display " ")
               (iter (cdr i)))))
    (iter dictionary)
    (newline)
    (next))

  ; Defered execution.
  (define (tick)
    (define name (parse! " "))
    (define entry (find name))
    (set! sp (cons entry sp))
    (next))
  (define (execute)
    (set! work (car sp))
    (set! sp (cdr sp))
    ((entry-action work)))
  (define (comma)
    (set! definition (vector-append definition (vector (car sp))))
    (set! sp (cdr sp))
    (next))

  ; Branching core.
  (define (here)
    (vector-length definition))
  (define (branch)
    (set! ip (vector-ref evec ip))
    (next))
  (define (0branch)
    (define top (car sp))
    (set! sp (cdr sp))
    (if (= 0 top)
        (set! ip (vector-ref evec ip))
        (set! ip (+ 1 ip)))
    (next))
  (define (+branch addr)
    (set! definition (vector-append definition (vector (make-word "branch" branch) addr))))
  (define (+0branch addr)
    (set! definition (vector-append definition (vector (make-word "0branch" 0branch) addr))))

  ; Branching words.
  (define (f-begin)
    (set! sp (cons (here) sp))
    (next))
  (define (ahead)
    (+branch 0)
    (set! sp (cons (- (here) 1) sp))
    (next))
  (define (again)
    (+branch (car sp))
    (set! sp (cdr sp))
    (next))
  (define (then)
    (vector-set! definition (car sp) (here))
    (set! sp (cdr sp))
    (next))
  (define (f-if)
    (+0branch 0)
    (set! sp (cons (- (here) 1) sp))
    (next))
  (define (until)
    (+0branch (car sp))
    (set! sp (cdr sp))
    (next))

  ; Evaluation.
  (define (eval1 name)
    (define entry (find name))
    (cond ((and (null? entry) (= state 0)) (set! sp (cons (string->number name) sp)))
          ((null? entry) (set! definition (vector-append definition (vector (make-word "dolit" dolit) (string->number name)))))
          ((or (= state 0) (entry-immediate? entry)) (begin (set! work entry) ((entry-action work))))
          (else (set! definition (vector-append definition (vector entry))))))
  (define (evaluate)
    (define name (parse! " "))
    (if (empty-string? name)
        #f
        (begin (set! ip 0)
               (set! evec (list->vector (list (make-word "nop" (lambda () '())))))
               (eval1 name)
               (evaluate))))

  ; Main entrypoint.
  (define (ok)
    (display "ok")
    (newline))
  (define (quit)
    (ok)
    (set! line (read-line))
    (evaluate)
    (quit))

  ; Stack manipulation helpers.
  (define (alter op) (lambda ()
    (op sp (lambda (nsp)
      (set! sp nsp)
      (next)))))
  (define (alter-rp op) (lambda ()
    (op sp rp (lambda (nsp nrp)
      (set! rp nrp)
      (set! sp nsp)
      (next)))))
  ; Unary and binary action helpers.
  (define (uniop op)
    (lambda ()
      (set! sp (cons (op (car sp)) (cdr sp)))
      (next)))
  (define (binop op)
    (lambda ()
      (set! sp (cons (op (cadr sp) (car sp)) (cddr sp)))
      (next)))

  (define dictionary (list
    (make-word "drop" (alter (lambda (sp k) (k (cdr sp)))))
    (make-word "dup" (alter (lambda (sp k) (k (cons (car sp) sp)))))
    (make-word "nip" (alter (lambda (sp k) (k (cons (car sp) (cdr sp))))))
    (make-word "over" (alter (lambda (sp k) (k (cons (cadr sp) sp)))))
    (make-word "swap" (alter (lambda (sp k) (k (cons (cadr sp) (cons (car sp) (cddr sp)))))))
    (make-word ">r" (alter-rp (lambda (sp rp k) (k (cdr sp) (cons (car sp) rp)))))
    (make-word "r>" (alter-rp (lambda (sp rp k) (k (cons (car rp) sp) (cdr rp)))))
    (make-word "r@" (alter-rp (lambda (sp rp k) (k (cons (car rp) sp) rp))))
    (make-word "negate" (uniop -))
    (make-word "+" (binop +))
    (make-word "-" (binop -))
    (make-word "*" (binop *))
    (make-word "/" (binop /))
    (make-word "=" (binop (lambda (a b) (if (= a b) -1 0))))
    (make-word "<>" (binop (lambda (a b) (if (= a b) 0 -1))))
    (make-word "<" (binop (lambda (a b) (if (< a b) -1 0))))
    (make-word ">" (binop (lambda (a b) (if (> a b) -1 0))))
    (make-word "<=" (binop (lambda (a b) (if (<= a b) -1 0))))
    (make-word ">=" (binop (lambda (a b) (if (>= a b) -1 0))))
    (make-word "and" (binop bitwise-and))
    (make-word "or" (binop bitwise-ior))
    (make-word "xor" (binop bitwise-xor))
    (make-word "cons" (binop cons))
    (make-word "car" (uniop car))
    (make-word "cdr" (uniop cdr))
    (make-word "pair" (binop cons))
    (make-word "unpair" (alter (lambda (sp k) (k (cons (car (car sp)) (cons (cdr (car sp)) (cdr sp)))))))
    (make-word "nil" (alter (lambda (sp k) (k (cons '() sp)))))
    (make-word "find" (alter (lambda (sp k) (k (cons (find (car sp)) (cdr sp))))))
    (make-word "." (alter (lambda (sp k) (begin (display (car sp)) (display " ") (k (cdr sp))))))
    (make-word "cr" (lambda () (newline) (next)))
    (make-word ".s" (alter (lambda (sp k) (begin (display (reverse sp)) (newline) (k sp)))))
    (make-word "'" tick)
    (make-word "execute" execute)
    (make-word "," comma)
    (make-word "see" see)
    (make-word "words" words)
    (make-word "exit" doexit)
    (make-word "bye" exit)
    (make-word "immediate" immediate)
    (make-word "]" compile)
    (make-word ":" colon)
    (make-immediate ";" semicolon)
    (make-immediate "[" interpret)
    (make-immediate "(" comment)
    (make-immediate "\"" dostring)
    (make-immediate "begin" f-begin)
    (make-immediate "ahead" ahead)
    (make-immediate "again" again)
    (make-immediate "then" then)
    (make-immediate "if" f-if)
    (make-immediate "until" until)
  ))

  (set! line (string-append
    ": square ( n -- n ) dup * ; "
    ": test1 0 begin dup . dup square . cr 1 + dup 11 = until drop ; "
  ))
  (evaluate)
  (quit)
)

(forth)
(exit)
